version: "3"

services:
  message-pusher:
    image: justsong/message-pusher
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      - TZ=Asia/Shanghai
      - SQL_DSN
      - SESSION_SECRET
      - REDIS_CONN_STRING
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro